/*
  CARGAR_ASIGNACION_SEMANAL
  Este procedimiento carga la asignacion de las ultimas dos semanas.
  Solo inserta los registros que no se encuentren aun en la tabla destino.
  Recalcula la planeacion para las semanas pasadas y configura las fechas de
  planeacion para ajustarse a la semana en curso;
  Este procedimiento solo debe correrse una vez se asegure que los datos de
  planeacion no van a cambiar
*/
CREATE OR REPLACE FUNCTION CARGAR_ASIGNACION_SEMANAL() RETURNS VOID AS $$
	DECLARE
		SEMANAS INTEGER[] := (
			SELECT ARRAY_AGG(PK_SEMANA)
			FROM(
				SELECT
					PK_SEMANA
				FROM MAESTRO.DIM_SEMANA
				WHERE COD_SEMANA < (
				    SELECT
				    	COD_SEMANA
				    FROM MAESTRO.DIM_SEMANA WHERE NOW() BETWEEN FECHA_INICIO AND FECHA_FIN 
				)
				ORDER BY COD_SEMANA DESC
				LIMIT 2
	  		)A
		);
		WEEK_START INTEGER := (SELECT TO_CHAR(FECHA_INICIO, 'YYYYMMDD')::INTEGER FROM MAESTRO.DIM_SEMANA DS WHERE CURRENT_DATE BETWEEN FECHA_INICIO AND FECHA_FIN);
		--DONT ITERATE OVER FUTURE PLANNING
		PLANNING_DATA CURSOR FOR SELECT * FROM PLANEACION.RECURSO WHERE FECHA_INICIO < TO_CHAR(CURRENT_DATE, 'YYYYMMDD')::INTEGER;
	BEGIN
		--LOAD ASSIGNATION
		INSERT INTO OPERACIONES.ASIGNACION
	    (FK_PERSONA, FK_PRESUPUESTO, FK_ROL, FK_SEMANA, FECHA, HORAS)
		SELECT
			R.FK_PERSONA,
	      	R.FK_PRESUPUESTO,
			R.FK_ROL,
			S.PK_SEMANA,
			TO_CHAR(S.FECHA_INICIO, 'YYYYMMDD')::INTEGER,
			SUM(RD.HORAS)
	    FROM PLANEACION.RECURSO R
	    JOIN PLANEACION.RECURSO_DETALLE RD
			ON RD.FK_RECURSO = R.PK_RECURSO
	    JOIN MAESTRO.DIM_SEMANA S
			ON TO_DATE(RD.FECHA::VARCHAR, 'YYYYMMDD') BETWEEN S.FECHA_INICIO AND S.FECHA_FIN
	    WHERE S.PK_SEMANA = ANY(SEMANAS)
	    AND R.FK_PERSONA||'_'||R.FK_PRESUPUESTO||'_'||R.FK_ROL||'_'||S.PK_SEMANA NOT IN (
			SELECT FK_PERSONA||'_'||FK_PRESUPUESTO||'_'||FK_ROL||'_'||FK_SEMANA
	      	FROM OPERACIONES.ASIGNACION
	      	WHERE S.PK_SEMANA = ANY(SEMANAS)
	    )
	    GROUP BY 
			R.FK_PERSONA,
			R.FK_PRESUPUESTO,
			R.FK_ROL,
			S.PK_SEMANA,
			S.FECHA_INICIO;
		
		--CLEAN PLANNING DETAIL
		--FIRST CAUSE OF CONSTRAINTS
		DELETE FROM PLANEACION.RECURSO_DETALLE
		WHERE FECHA <= (
			SELECT TO_CHAR(MAX(FECHA_FIN), 'YYYYMMDD')::INTEGER
			FROM MAESTRO.DIM_SEMANA
			WHERE PK_SEMANA = ANY(SEMANAS)
		);
	
		--UPDATE PLANNING
		FOR PLANNING_ROW IN PLANNING_DATA LOOP
			IF PLANNING_ROW.FECHA_FIN < WEEK_START THEN
				DELETE FROM PLANEACION.RECURSO
				WHERE CURRENT OF PLANNING_DATA;
			ELSIF PLANNING_ROW.FECHA_INICIO <= WEEK_START THEN
				UPDATE PLANEACION.RECURSO
				SET
					FECHA_INICIO = WEEK_START,
					HORAS = (
						SELECT 
							SUM(1) * 9 * R.PORCENTAJE / 100
						FROM PLANEACION.RECURSO R
						JOIN MAESTRO.DIM_TIEMPO T
							ON T.COD_FECHA BETWEEN R.FECHA_INICIO AND R.FECHA_FIN
							AND R.PK_RECURSO = PLANNING_ROW.PK_RECURSO
						WHERE EXTRACT(ISODOW FROM T.FECHA) NOT IN (6,7)
						AND T.BAN_FESTIVO = FALSE
						GROUP BY R.PORCENTAJE
					)
				WHERE CURRENT OF PLANNING_DATA;
			END IF;
		END LOOP;
	END;
$$ LANGUAGE PLPGSQL;